### ISSUE TITLE
Broken Links in README.md

### ISSUE THREAD

**Issue by ps-19** [Mboalab/Mboalab_Outreachy-May-Aug-2022#83]
https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/blob/main/README.md

Multiple links are broken if anyone wants to work upon the issue it is open to work. The issue is **very naive** and **very simple** to solve.
<br/>
<br/>

 
![Screenshot (4)](https://user-images.githubusercontent.com/63330165/164072800-10a4228e-224c-4050-adf5-6d84898da20f.png)

**Comment by tejaswari7** [comment]
I would like to take this issue

**Comment by ps-19** [comment]
Sure!!

**Comment by richarddushime** [comment]
i had worked on this issue in the [PR](https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/pull/14) the broken Links that were in Read me Files

**Comment by ps-19** [comment]
sure, @richarddushime you have worked on broken links but not mentioned in this issue.

**Comment by ps-19** [comment]
You can click on marked circle in the screenshot it direct to incorrect site.

**Comment by richarddushime** [comment]
Yeah true Thanks

**Comment by tejaswari7** [comment]
I found some links 
[LinkedIn](https://www.linkedin.com/company/mboalab/)
[https://website-mboalab.vercel.app/](https://website-mboalab.vercel.app/) instead of [https://www.mboalab.africa/](https://www.mboalab.africa/)

I hope I found correct links for LinkedIn and official website!!
Where can I find link for Instagram page, I searched for it but was not able to find it.

**Comment by ps-19** [comment]
@tejaswari7 nice!!

**Comment by tejaswari7** [comment]
@ps-19 I created [PR](https://github.com/Mboalab/Mboalab_Outreachy-May-Aug-2022/pull/114)
please review it

**Comment by ps-19** [comment]
I can not review a PR i don't have access to do that.

**Comment by tejaswari7** [comment]
> I can not review a PR i don't have access to do that.
okay!!
